language: go
go:
  - 1.5
  - 1.6
before_install:
  - sudo apt-get update
  - go get github.com/mattn/gom
script:
  - pushd $TRAVIS_BUILD_DIR
  - make test
  - make deb
  - popd
notifications:
  email: false
