###
# Main server configuration
###
name:  "statsgod"
host:  localhost
port:  8125
debug: false

###
# Backend relay carbon server configuration
###
carbonHost: localhost
carbonPort: 5001

###
# Relay connection options
###
relayConcurrency: 1
relayTimeout: 20s

###
# Flush options
###
flushInterval: 10s
percentile: 80
