###
# Main server configuration
###
service:
    name: statsgod

###
# Socket connections
###
connection:
    tcp:
        host: 127.0.0.1
        port: 8125
    udp:
        host: 127.0.0.1
        port: 8126
    unix:
        file: /var/run/statsgod.sock

###
# Backend relay carbon server configuration
###
carbon:
   host: 127.0.0.1
   port: 2003

###
# Relay connection options
###
relay:
    type: carbon   # One of "mock" or "carbon".
    concurrency: 1 # Normally use 1 for carbon.
    timeout: 30s   # How long to sit idle on a connection.
    flush: 10s     # How frequently to flush to the relay.

###
# Stats options
###
stats:
    percentile: 80

###
# Debug options
###
debug:
    verbose: false # Increases the logging output.
    receipt: false # Logs a message with the parsed metric.
    profile: false # Profile the program with runtime/pprof.
    relay: false   # Relay internal runtime information as metrics.
